### ISSUE TITLE
Move to SKLL v2.0

### ISSUE THREAD

**Issue by jbiggsets** [EducationalTestingService/rsmtool#311]
We should use the latest release of `skll`.

**Comment by desilinguist** [comment]
As part of this, we should also move the RSMTool package to `ets` channel instead of the `desilinguist` channel.

**Comment by aloukina** [comment]
Changes that likely affect RSMTool:
* Configuration field objective has been deprecated and replaced with objectives which allows specifying multiple tuning objectives for grid search (Issue #381, PR #458).
* There are no longer any default grid search objectives since the choice of objective is best left to the user. Note that since grid search is enabled by default, you must either choose an objective or explicitly disable grid search (Issue #381, PR #458).
* mean_squared_error is no longer supported as a metric. Use neg_mean_squared_error instead (Issue #382, PR #470).

Changes that might be useful:
* SKLL models now have a new pipeline attribute which makes it easy to manipulate and use them in scikit-learn, if needed (Issue #451, PR #474).

**Comment by aloukina** [comment]
#339  identified two issues: (1) Several errors due to change in pearsonr in scipy (#343 ); (2) Error in pca (#347 ).

We also need to re-train all models stored in tests for RSMPredict (#344).

**Comment by desilinguist** [comment]
Addressed by #349.
