### ISSUE TITLE
Add crossvalidation

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#353]
Crossvalidation is one of the most requested features.
The simplest version will be:
- Expose whatever options SKLL has for folds. The minimal solution is to allow user to specify N folds or specific folds.
- Train models by fold and save evaluation outputs for each fold.
- Do one (or both) of the following:
       - Pull all predictions into a single file and generate rsmeval report. 
       - Generate rsmsummarize report for individual folds. 
- If requested, train final model on the whole dataset and generate the first part of rsmtool report with model detail/feature descriptives. 

Few issues that would need to be considered is:
- Do we want all intermediate results for all folds (we should probably skip the reports), the by-fold evaluation files are useful.
- In future there could be a more customized CV report. 
- Do we need more machinery for parallelization?

**Comment by desilinguist** [comment]
The plan looks pretty good!

Right now, we are doing grid search with a [single process](https://github.com/EducationalTestingService/rsmtool/blob/master/rsmtool/modeler.py#L1122) - for XVAL, we would definitely need to think a bit more about parallelization otherwise things might be very, very slow.

It would be a bad idea to mix parallelization and report generation so we would certainly need to skip the reports for the individual folds.
