### ISSUE TITLE
Log capture in tests for interactive generation

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#424]
Currently if tests such as ` test_cli.TestToolCLI.test_generate_with_groups('rsmcompare', 'generate --subgroups', None, None)` fail, you get `subprocess.CalledProcessError: Command '['rsmcompare', 'generate', '--subgroups']' returned non-zero exit status 1.` Could we capture the actual error message before the exit status?

**Comment by desilinguist** [comment]
The `subprocess.CalledProcessError` exception  is raised _not_ when the tests fail but when rather when there is an error in the test command being run.

I will modify the subprocess call in this test to capture the STDERR stream  so that one can easily use `nosetests --pdb-errors` to examine the `stderr` variable in the PDB session and figure out why the tests are erroring.
