### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by bndgyawali** [EducationalTestingService/rsmtool#52]
While running `rsmcompare`, the file name became too long and it threw an error. It might be better if we could supply optional parameter `report_name` in the config file so it does not have the issue of long file name.

**Comment by desilinguist** [comment]
I can see how this can be annoying if you get the error after `rsmcompare` has done all the work and it fails when writing it out. So, it would be better if the user was notified pretty much immediately that the default `rsmcompare` name wouldn't work.

I think the easiest way to do this would be to have a `--name` option for `rsmcompare`. When it starts up, it can check whether the default name it comes up with will be "too long" and if so, it can raise an error right at the beginning and ask the user to use the `--name` flag instead. 

How do we define whether something is too long? Looking at the CSVs and figures we produce, it looks like 210 characters is about the limit for the `experiment_id` since the longest prefix we add is about 40 characters and the 255 is the limit for most filesystems. 

I will add a test so that if we add new CSV files or figures in the future, that test will fail and require us to update the length threshold.

**Comment by aloukina** [comment]
So what we are thinking of doing is to add a new field ``comparison_id`` to the config file with the report named``$ID_report.html``. If in future we decide to save any output files, those would be named ``$ID_$SOMETHING.csv``.

**Comment by desilinguist** [comment]
Yeah, I like that idea better than mine. I will work on this.

**Comment by desilinguist** [comment]
Addressed by #61.
